services:
  frontend-billing-console-server:
    image: ghcr.io/forepath/agenstra-billing-console-server:latest
    container_name: billing-console-server
    environment:
      # Frontend server configuration
      HOST: 0.0.0.0
      PORT: 4500
      NODE_ENV: production
      DEFAULT_LOCALE: en
    ports:
      - '4500:4500'
    networks:
      - billing-console-network
    restart: unless-stopped

networks:
  billing-console-network:
    driver: bridge
